// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlgw0A4-DqEvwGnafwAMbCxRyTQ4KaI2o',
    appId: '1:715138194640:web:1385439b1216d76b0052d5',
    messagingSenderId: '715138194640',
    projectId: 'neverforgetnew',
    authDomain: 'neverforgetnew.firebaseapp.com',
    storageBucket: 'neverforgetnew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmvBb0b2gwGh2F7vIJ9-EJdsFFOv8xvt0',
    appId: '1:715138194640:android:2907db4dae18a9330052d5',
    messagingSenderId: '715138194640',
    projectId: 'neverforgetnew',
    storageBucket: 'neverforgetnew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5mjImFYq1tvDR1BKICnyu3EbEC9T_NiQ',
    appId: '1:715138194640:ios:9aec236a4ecb7fad0052d5',
    messagingSenderId: '715138194640',
    projectId: 'neverforgetnew',
    storageBucket: 'neverforgetnew.appspot.com',
    iosClientId: '715138194640-kpacqla6enu2jjrrjqfhckd7c3en34ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.neverForget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5mjImFYq1tvDR1BKICnyu3EbEC9T_NiQ',
    appId: '1:715138194640:ios:9aec236a4ecb7fad0052d5',
    messagingSenderId: '715138194640',
    projectId: 'neverforgetnew',
    storageBucket: 'neverforgetnew.appspot.com',
    iosClientId: '715138194640-kpacqla6enu2jjrrjqfhckd7c3en34ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.neverForget',
  );
}
